namespace Teknomli
{
    /*internal class Letter
    {

        public static string ConvertKeyCode(Keys key, bool isShift)
        {
            if (isShift)
            {
                return key switch
                {
                    Keys.A => "A",
                    Keys.B => "B",
                    Keys.C => "C",
                    Keys.D => "D",
                    Keys.E => "E",
                    Keys.F => "F",
                    Keys.G => "G",
                    Keys.H => "H",
                    Keys.I => "I",
                    Keys.J => "J",
                    Keys.K => "K",
                    Keys.L => "L",
                    Keys.M => "M",
                    Keys.N => "N",
                    Keys.O => "O",
                    Keys.P => "P",
                    Keys.Q => "Q",
                    Keys.R => "R",
                    Keys.S => "S",
                    Keys.T => "T",
                    Keys.U => "U",
                    Keys.V => "V",
                    Keys.W => "W",
                    Keys.X => "X",
                    Keys.Y => "Y",
                    Keys.Z => "Z",
                    Keys.D0 => "zero",
                    Keys.D1 => "!",
                    Keys.D2 => "\"",
                    Keys.D3 => "#",
                    Keys.D4 => "$",
                    Keys.D5 => "%",
                    Keys.D6 => "&",
                    Keys.D7 => "'",
                    Keys.D8 => "(",
                    Keys.D9 => ")",
                    Keys.OemMinus => "=",
                    Keys.Oem7 => "~",
                    Keys.Oem5 => "|",
                    Keys.Oemtilde => "`",
                    Keys.OemOpenBrackets => "{",
                    Keys.Oem6 => "}",
                    Keys.Oemplus => "+",
                    Keys.Oem1 => "*",
                    Keys.OemQuestion => "?",
                    Keys.OemBackslash => "_",
                    Keys.Space => " ",
                    Keys.Enter => "enter",
                    Keys.Control => "ctrl",
                    Keys.OemPeriod => ">",
                    Keys.Oemcomma => "<",
                    Keys.Left => "left",
                    Keys.Right => "right",
                    _ => "null"
                };
            }
            return key switch
            {
                Keys.A => "a",
                Keys.B => "b",
                Keys.C => "c",
                Keys.D => "d",
                Keys.E => "e",
                Keys.F => "f",
                Keys.G => "g",
                Keys.H => "h",
                Keys.I => "i",
                Keys.J => "j",
                Keys.K => "k",
                Keys.L => "l",
                Keys.M => "m",
                Keys.N => "n",
                Keys.O => "o",
                Keys.P => "p",
                Keys.Q => "q",
                Keys.R => "r",
                Keys.S => "s",
                Keys.T => "t",
                Keys.U => "u",
                Keys.V => "v",
                Keys.W => "w",
                Keys.X => "x",
                Keys.Y => "y",
                Keys.Z => "z",
                Keys.D0 => "0",
                Keys.D1 => "1",
                Keys.D2 => "2",
                Keys.D3 => "3",
                Keys.D4 => "4",
                Keys.D5 => "5",
                Keys.D6 => "6",
                Keys.D7 => "7",
                Keys.D8 => "8",
                Keys.D9 => "9",
                Keys.OemMinus => "-",
                Keys.Oem7 => "^",
                Keys.Oem5 => "\\",
                Keys.Oemtilde => "@",
                Keys.OemOpenBrackets => "[",
                Keys.Oem6 => "]",
                Keys.Oemplus => ";",
                Keys.Oem1 => ":",
                Keys.OemQuestion => "/",
                Keys.OemBackslash => "\\",
                Keys.Space => " ",
                Keys.Enter => "enter",
                Keys.Control => "ctrl",
                Keys.OemPeriod => ".",
                Keys.Oemcomma => ",",
                Keys.Left => "left",
                Keys.Right => "right",
                Keys.Back => "back",
                _ => "null"
            };
        }
        private static void ReplaceLetters(ref string ltr)
        {
            ltr = ltr switch
            {
                "?" => "que",
                "!" => "exc",
                "\"" => "quo",
                "#" => "has",
                "$" => "dol",
                "%" => "per",
                "&" => "and",
                "'" => "sin",
                "(" => "brs",
                ")" => "bre",
                "`" => "bkt",
                "\\" => "bsl",
                "{" => "cbs",
                "}" => "cbe",
                "/" => "sla",
                "+" => "plu",
                "-" => "min",
                "*" => "ast",
                "." => "dot",
                "," => "com",
                " " => "spa",
                ">" => "gre",
                "<" => "les",
                "=" => "equ",
                "彩" => "sai",
                _ => ltr
            };
        }
    }*/
}
